PKG_NAME=yacoap
PKG_URL=https://github.com/Gr3yh0und/YaCoAP
PKG_VERSION=4298bb2fc241d7a0a067068d946a9b4ab26923be
PKG_LICENSE=MIT

.PHONY: all

all: git-download
	"$(MAKE)" -C $(PKG_BUILDDIR)

include $(RIOTBASE)/pkg/pkg.mk
